00:55:58 - ERR - post - ("Error al validar el request -> {'login_password': ['Missing data for required field.'], 'login_pass': ['Unknown field.']}",)
00:59:08 - ERR - post - ("Error al validar el request -> {'login_password': ['Missing data for required field.'], 'login_pass': ['Unknown field.']}",)
01:55:46 - ERR - post - ("Error al validar el request -> {'login_password': ['Missing data for required field.'], 'login_user': ['Missing data for required field.'], 'username': ['Unknown field.'], 'password': ['Unknown field.']}",)
01:56:49 - ERR - post - ("Error al validar el request -> {'login_password': ['Missing data for required field.'], 'login_user': ['Missing data for required field.'], 'username': ['Unknown field.'], 'password': ['Unknown field.']}",)
02:27:01 - ERR - Login - (KeyError(0),)
02:27:01 - ERR - post - (TypeError('response_success() takes 1 positional argument but 2 were given'),)
02:27:53 - ERR - Login - (KeyError(0),)
02:27:53 - ERR - post - (TypeError('response_success() takes 1 positional argument but 2 were given'),)
02:33:45 - ERR - Login - (KeyError(0),)
02:33:45 - ERR - post - (TypeError('response_success() takes 1 positional argument but 2 were given'),)
02:33:46 - ERR - Login - (KeyError(0),)
02:33:46 - ERR - post - (TypeError('response_success() takes 1 positional argument but 2 were given'),)
02:34:31 - ERR - Login - (KeyError(0),)
02:34:31 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:26 - ERR - Login - (KeyError(0),)
02:37:26 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:28 - ERR - Login - (KeyError(0),)
02:37:28 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:28 - ERR - Login - (KeyError(0),)
02:37:28 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:28 - ERR - Login - (KeyError(0),)
02:37:28 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:28 - ERR - Login - (KeyError(0),)
02:37:28 - ERR - post - (TypeError("'dict' object is not callable"),)
02:37:28 - ERR - Login - (KeyError(0),)
02:37:28 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:23 - ERR - Login - (KeyError(0),)
02:41:23 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:24 - ERR - Login - (KeyError(0),)
02:41:24 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:24 - ERR - Login - (KeyError(0),)
02:41:24 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:24 - ERR - Login - (KeyError(0),)
02:41:24 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:25 - ERR - Login - (KeyError(0),)
02:41:25 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:25 - ERR - Login - (KeyError(0),)
02:41:25 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:25 - ERR - Login - (KeyError(0),)
02:41:25 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:25 - ERR - Login - (KeyError(0),)
02:41:25 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:25 - ERR - Login - (KeyError(0),)
02:41:25 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:26 - ERR - Login - (KeyError(0),)
02:41:26 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:26 - ERR - Login - (KeyError(0),)
02:41:26 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:26 - ERR - Login - (KeyError(0),)
02:41:26 - ERR - post - (TypeError("'dict' object is not callable"),)
02:41:27 - ERR - Login - (KeyError(0),)
02:41:27 - ERR - post - (TypeError("'dict' object is not callable"),)
